name: mic_test_app
description: A minimal Flutter iOS mic‑recording test
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.13+1
  permission_handler: ^11.3.1
  path_provider: ^2.1.2

flutter:
  uses-material-design: true